### ISSUE TITLE
Pharo-4.0 test failing ...

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/metacello-work#323]
from [test](https://travis-ci.org/dalehenrich/metacello-work/jobs/47979802):

```
**************************************************************************************
	Results for #('BaselineOfMetacello') Test Suite
558 run, 557 passes, 0 skipped, 0 expected failures, 0 failures, 1 errors, 0 unexpected passes
**************************************************************************************
*** ERRORS *******************
	MetacelloGoferFunctionalTest debug: #testCommitNewPackageSpec.
**************************************************************************************
```

**Comment by dalehenrich** [comment]
@demarey have there been recent changes (as of today?) to gofer for 4.0 ... The [Pharo-4.0 tests passed 3 days ago](https://travis-ci.org/dalehenrich/metacello-work/builds/47525500) and now they are consistently failing ....

**Comment by dalehenrich** [comment]
It turns out that the test is failing because of a MNU: `testCommitNewPackageSpec Error: MessageNotUnderstood: MCClassDefinition>>createClass` ... is that something that has changed long term for Pharo-4.0?

**Comment by demarey** [comment]
Hi Dale,

Indeed, there was a change done yesterday. You can see the diff here: https://github.com/pharo-project/pharo-core/commit/347681dfc4e591fec6ba16fd3a5a28f0cf2c583d. It is good to catch this problem early.
It looks like there is only one test failing: ```MetacelloGoferFunctionalTest debug: #testCommitNewPackageSpec```. I will report this problem. Thanks

**Comment by dalehenrich** [comment]
Thanks @demarey I've put in an expectedFailure for Pharo4.0 for that test so we can hve lush green-ness ... I think that that method is only used in that particular test so if it is permanent, we can change the tests ...

**Comment by demarey** [comment]
Marcus integrated a fix for this test. Your tests should be back to green for Pharo 4.0 now.

**Comment by dalehenrich** [comment]
Thanks @demarey! I'll remove the expected failure when I get the chance.

**Comment by dalehenrich** [comment]
expected failures removed: 678375c81f04b0917caa0074475e378d29cf53ab
