### ISSUE TITLE
1.0-beta.32.1 broken for Squeak 4.5/Trunk

### ISSUE THREAD

**Issue by fniephaus** [dalehenrich/metacello-work#333]
Hi Dale,

I just tried to load MetacelloPreview in a Squeak Trunk image, but it looks like `1.0-beta.32.1` is broken for some reason. Everything works fine when using `1.0-beta.32` instead of `#'previewBootstrap'`.

Sorry, but I didn't have enough time to investigate the problem any further...

Cheers,
Fabio

**Comment by dalehenrich** [comment]
Fabio,

If it's the trunk, then it is likely that something changed in Squeak 
that broke Metacello ... either the change was intentional (in which 
case Metacello will have to change) or it was unintentional and we'll 
have to wait for Squeak to change ...

Right at this moment I do not have any spare time to chase down a 
Metacello problem in Squeak-Trunk:(, so hopefully you or someone else 
will be able to characterize the problem ..

Thanks for the report, tho.

Dale

**Comment by fniephaus** [comment]
You're probably right, I just wanted to write this down quickly, so we don't forget about it.

If this continues to be a problem and if I have some more time, I'll try to track it down and fix it for us.

Regards,
Fabio

**Comment by dalehenrich** [comment]
Excellent!

**Comment by fniephaus** [comment]
Hi Dale,

Just loaded an Squeak 4.5 All-In-One and ran into the same problem again:
![screenshot 2015-04-01 16 23 01](https://cloud.githubusercontent.com/assets/2368856/6942993/6ba3228e-d88b-11e4-91c4-fa0863e29a77.png)

I might find some time later this week to investigate the problem...

**Comment by dalehenrich** [comment]
Fabio,

"no certificate provided"  looks like a "problem" related to the SSH 
plugin when trying to download the zip file from github using https ...

I think @krono has experience in this area ... do you happen to be 
working on a mac?

**Comment by krono** [comment]
It is the SSL thing, yes.
Somehow the metacello bootstrap still does not load the latest WebClient during bootstrap.
I slipstreamed the change into  1.0-beta.32.1 here in the repo. Has it already made it to ss3?

**Comment by dalehenrich** [comment]
Ah ... then this is in my court (sheepish grin) ... well as you know, 
I'll have this deployed in a year and a half:)

I've put it on my short list, so I should be able to get this addressed 
within the week ...

Dale

**Comment by dalehenrich** [comment]
@fniephaus ... fixed Issue #322 ... hopefully this will take of your issue ....

**Comment by fniephaus** [comment]
Thanks, Dale! Works like a charm

**Comment by dalehenrich** [comment]
Haha, Thank @krono:)

**Comment by fniephaus** [comment]
I will when I see him tomorrow :)
