### ISSUE TITLE
Loading Grease in Squeak 5 using Metacello is broken

### ISSUE THREAD

**Issue by jbrichau** [dalehenrich/metacello-work#381]
Hi guys,

The 'advised' way of loading Grease (and Seaside) in Squeak 5 does not work anymore since I introduced a separate Metacello spec for Squeak 5 in ConfigurationOfGrease:

```
Installer squeaksource 
     project: 'MetacelloRepository'; 
     install: 'ConfigurationOfGrease'. 
((Smalltalk at: #ConfigurationOfGrease) project version: '1.2.5') load:'Tests'
```
The `Grease-Squeak5-Core` is not loaded. It seems the platform symbol is not detected in the Metacello version that is used. In contrast, loading with the 'new' Metacello API works (according to @krono):

```
Metacello new
	configuration: 'Grease';
	version: '1.2.5';
	load: #(Tests)
```
Would be great to have this fixed for Squeak 5 so loading Grease works correctly again.

**Comment by jbrichau** [comment]
Mind that I reverted the stable version for Squeak to a configuration where the Squeak5 platform symbol is not used, until we can fix or advise a way to work with the newer versions.

**Comment by krono** [comment]
Thanks, Johan. This is related to #365 and especially #366.

@dalehenrich What are the odd that adding the platform attributes to the non-preview version is easy?

**Comment by dalehenrich** [comment]
@krono You just need to slipstream the Squeak 5.0 changes into Metacello 1.0-beta.32.1. I think after your WebClient changes back in January, you should have permissions to all up and down the the line ...

Is there are reason that this is still the "advised way" for loading configurations?

```
Installer squeaksource 
     project: 'MetacelloRepository'; 
     install: 'ConfigurationOfGrease'. 
((Smalltalk at: #ConfigurationOfGrease) project version: '1.2.5') load:'Tests'
```

It is very likely that the ConfigurationOfGrease may start using constructs that are not available or even worse buggy in the non-preview version of Metacello .... 

I don't recommend that anyone actually use the non-preview version of Metacello (Metacello 1.0-beta.32.1) for anything other than bootstrapping Metacello from GitHub ...

**Comment by jbrichau** [comment]
This issue can be closed. Loading Metacello in Squeak5 using the instructions at https://github.com/dalehenrich/metacello-work and then using the preview version of Metacello 
```
Metacello new
    configuration: 'Grease';
    version: '1.2.5';
    load: #(Tests)
```
 works just fine.
