### ISSUE TITLE
Cannot load metacello-work in Squeak image

### ISSUE THREAD

**Issue by fniephaus** [dalehenrich/metacello-work#389]
When I execute [this](https://github.com/dalehenrich/metacello-work#squeak), I now get a timeout, because http://seaside.gemstone.com is not available.

**Comment by dalehenrich** [comment]
Do you have a stack? I'd guess that the timeout is occurring  in `Installer gemSource` and I don't maintain that code ...

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/14289697/42be6a46-fb5c-11e5-9d97-af5b81f15713.png)

> PING seaside.gemstone.com (64.20.104.5): 56 data bytes

Looks like seaside.gemstone.com

**Comment by krono** [comment]
This should really not happen.

Also, Travis is Fine.

@fniephaus can you give us the list of all your repositories in the image?

**Comment by dalehenrich** [comment]
I understand that you are hitting http://seaside.gemstone.com ... I was asking for stack so that I could tell where the url is coming from ... my suspicion is that `Installer gemSource` is using http://seaside.gemstone.com instead of http://seaside.gemtalksystems.com ... a stack would help tell me whether this is likely to be true or not ...

**Comment by krono** [comment]
As I said on squeak-dev, if this image is younger than march 2015, it cannot be `Installer gemsource`.
What _I_ suspect is that some other package put that url into the repository list and now is queried when someone tries to update the packages lists

**Comment by dalehenrich** [comment]
... and a stack will provide the information needed to know where the url is coming from ... it's nice to know that `Installer gemSource` is correct :)

**Comment by fniephaus** [comment]
http://seaside.gemstone.com is back online, so I can't reproduce the issue atm...

**Comment by fniephaus** [comment]
FYI: https://github.com/dalehenrich/metacello-work/search?p=1&q=%22seaside.gemstone.com%22&utf8=%E2%9C%93

**Comment by fniephaus** [comment]
@krono 
Also:
![image](https://cloud.githubusercontent.com/assets/2368856/14296640/51e95f20-fb7b-11e5-80fa-1763084db39b.png)

**Comment by dalehenrich** [comment]
Okay ... that seals the deal ... `Installer class>>gemSource` is the source of the bad url ... stack not needed anymore ...

**Comment by krono** [comment]
yes; it is. Sorry Dale.

**Comment by dalehenrich** [comment]
Haha, no problem ... better to submit a bug that is not one that to **not** submit a bug that is one!
