### ISSUE TITLE
MCGitHubRepository cacheDirectory not honored

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/metacello-work#407]
Looks like there is a setting for Pharo:

```MCGitHubRepository cacheDirectory: '/Users/mariano/Pharo/localRepo/' asFileReference.```

But seems ignored when I load something from github. In my example, from ConfigurationOfMyAPP, I am defining:

		
		spec baseline: 'OSSubprocess' with: [
    		spec repository: 'github://marianopeck/OSSubprocess:master/repository' ].

But even with that, the zip ends up in the directory where the .image is.

**Comment by dalehenrich** [comment]
The.zip file is supposed to be downloaded into /tmp (see Issue #405 and #406) the cacheDirectory only controls the location of the actual unzipped filetree cache ... presumably the unzipped filetree **is** put into the cache directory?

**Comment by marianopeck** [comment]
OK, I understand now. So then it seems my issue is then #405 ?

**Comment by dalehenrich** [comment]
Yes ... as long as the unzipped filetree is going to the right place ...

Dale

**Comment by marianopeck** [comment]
Yes, those seem to be going to the correct place :)

**Comment by dalehenrich** [comment]
ah, good!
