### ISSUE TITLE
github url and branch names that include $/

### ISSUE THREAD

**Issue by zecke** [dalehenrich/metacello-work#411]
In may projects it is coming to have semantic branch names like "release/XYZ". When trying to use:

```
baseline: 'SMPP' with: [
    spec repository: 'github://moiji-mobile/smpp-codec:release/10/mc' ];
```

it fails as it is not clear if the branch is "release/10" and the directory "mc" or if it is "release" and "10/mc". Could you consider using something like?

```
baseline: 'SMPP' with: [
    spec repository: 'github://moiji-mobile/smpp-codec?branch=release/10&path=mc' ];
```

**Comment by krono** [comment]
you can escape via `\`:

```
baseline: 'SMPP' with: [
    spec repository: 'github://moiji-mobile/smpp-codec:release\/10/mc' ];
```

**Comment by zecke** [comment]
I tried that with Pharo-3.0 and it failed but it does work in Pharo-5.0.. thank you for the quick answer.. Will start using it once dropping Pharo-3.0 support.

**Comment by dalehenrich** [comment]
Holger,

I would think it would work in Pharo-3.0, but it is probably necessary 
to load the latest version of Metacello to get the feature ...

Dale
