### ISSUE TITLE
Cannot install Metacello in Squeak VM

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [dalehenrich/metacello-work#427]
I am simply taking what the readme says:

    "Get the Metacello configuration (for Squeak users)"
    Installer gemsource
        project: 'metacello';
        addPackage: 'ConfigurationOfMetacello';
        install.
    
    "Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
    ((Smalltalk at: #ConfigurationOfMetacello) project 
      version: #'previewBootstrap') load.
    
    "Load the Preview version of Metacello from GitHub"
    (Smalltalk at: #Metacello) new
      configuration: 'MetacelloPreview';
      version: #stable;
      repository: 'github://dalehenrich/metacello-work:configuration';
      load.
    
    "Now load latest version of Metacello"
    (Smalltalk at: #Metacello) new
      baseline: 'Metacello';
      repository: 'github://dalehenrich/metacello-work:master/repository';
      get.
    (Smalltalk at: #Metacello) new
      baseline: 'Metacello';
      repository: 'github://dalehenrich/metacello-work:master/repository';
      load.

Paste it into a workspace of a newly downloaded Squeak:

![squeak1](https://cloud.githubusercontent.com/assets/11130348/23179831/9229f742-f86f-11e6-8b2f-ddacddbabff8.png)

Select all code and do right click "do it". Then the following error appears:

![squeak2](https://cloud.githubusercontent.com/assets/11130348/23179858/a60cf11a-f86f-11e6-86e5-fc5385b1e4cc.png)

The last time I used Squeak, Smalltalk or any of the tools involved here was years ago and I don't know if some prerequisite is missing or what I am doing wrong. Actually I only wanted to install Koans, for which I seem to need Metacello(?).

**Comment by krono** [comment]
This typically means that a zip file was not correctly downloaded.

Can you please do-it all statements individually, so that we see _where_ the error occurs?

**Comment by ZelphirKaltstahl** [comment]
@krono Good to know this is still active.

It shows some unexpected behavior at the second step, when I run:

    "Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
    ((Smalltalk at: #ConfigurationOfMetacello) project 
      version: #'previewBootstrap') load.

It turns into:

    "Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
    ((Smalltalk at: #ConfigurationOfMetacello) project 
       Nothing more expected ->version: #'previewBootstrap') load.

Seems like some syntax error. Maybe since that cannot be run properly the later steps fail?
Also I noticed that there is one additional pair of parentheses in this seccond step compared to the other steps. If I make it look like this:

    "Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
    (Smalltalk at: #ConfigurationOfMetacello) project 
      version: #'previewBootstrap' load.

I get:

![image](https://cloud.githubusercontent.com/assets/11130348/23190335/87bda4ca-f897-11e6-8f08-d5d717f9a8d1.png)

**Comment by krono** [comment]
So the steps depend on each other.

First, please execute 
```Smalltalk
Installer gemsource
    project: 'metacello';
    addPackage: 'ConfigurationOfMetacello';
    install.
```

Then
```Smalltalk
((Smalltalk at: #ConfigurationOfMetacello) project 
  version: #'previewBootstrap') load.
```

Then
```Smalltalk
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  get.
```
and
```Smalltalk
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  get.
```

In which of the four do-its does the `dNU` appear?

**Comment by ZelphirKaltstahl** [comment]
At step two:

    ((Smalltalk at: #ConfigurationOfMetacello) project 
      version: #'previewBootstrap') load.

The workspace content becomes:

    ((Smalltalk at: #ConfigurationOfMetacello) project 
       Nothing more expected ->version: #'previewBootstrap') load.

For the other steps Squeak "selects" the last work when I run them. So for example when I run step 1:

    Installer gemsource
        project: 'metacello';
        addPackage: 'ConfigurationOfMetacello';
        install.

It selects `install.` - not sure if this selection has any meaning. I don't know how to view the output of the code, if there is any. I tried appending `Transcript show:` in front, but it does not show any output in the Transcript window.

**Comment by krono** [comment]
Am 22. Februar 2017 08:30:47 MEZ schrieb Zelphir Kaltstahl <notifications@github.com>:
>At step two:
>
>    ((Smalltalk at: #ConfigurationOfMetacello) project 
>      version: #'previewBootstrap') load.
>
>The workspace content becomes:
>
>    ((Smalltalk at: #ConfigurationOfMetacello) project 
>       Nothing more expected ->version: #'previewBootstrap') load.
>
>For the other steps Squeak "selects" the last work when I run them. So
>for example when I run step 1:
>
>    Installer gemsource
>        project: 'metacello';
>        addPackage: 'ConfigurationOfMetacello';
>        install.
>
>It selects `install.` - not sure if this selection has any meaning. I
>don't know how to view the output of the code, if there is any. I tried
>appending `Transcript show:` in front, but it does not show any output
>in the Transcript window.

you have to select the whole  code for each step, not just the last line ☺
-- 
Sent from mobile device

**Comment by ZelphirKaltstahl** [comment]
What I mean is, that the last line "selects itself" when I run the code, which I select in total, for each step. I don't know why it does that. I also tried not using right click and using `ctrl+d`, same effect.

**Comment by krono** [comment]
This "selects itself" typically only happens, when you do _not_ select the code but press `ctrl-d` (or do-it w/ right-click) somewhere in that line without a selection.

What happens if you
 * Copy the second do-it to an empty worspace
 * `ctrl-a` for select all
 * `ctrl-d` for do-it?

(I just tried in a current Squeak and it should work)

**Comment by ZelphirKaltstahl** [comment]
@krono Updated the post : )

**Comment by krono** [comment]
In the Debugger, please
 1. Click on 'Debug'
 2. Right-click on the Stack trace
 3. Click 'mail out bug report'
 4. Enter something (does not matter) and accept
 5. Copy the contents of the 'Mister Postman' window

Please put it into a [Gist](https://gist.github.com/) or something  and link it here :)

**Comment by ZelphirKaltstahl** [comment]
Here is the [Gist](https://gist.githubusercontent.com/ZelphirKaltstahl/73eb0ab72d337336f7ebeadb3d0b453f/raw)

I also clicked the "Full Stack" button.

**Comment by krono** [comment]
Thanks for the information.

Ok, monticello tries to write the file `ConfigurationOfMetacello-topa.802.mcz` to `/home/xiaolong/apps/Squeak5.1-16548-32bit-Linux/shared/package-cache`. Does such a file already exist there? do you have write permissions on the directory?

**Comment by ZelphirKaltstahl** [comment]
There is no such file, there is only a file named: `Morphic-mt.1296(mt.1295).mcd`. This file is owned by root and group is also root.

If this helps: Before the error appears, Squeak shows a first loading bar, which completes, then shows a second one, which almost finishes, but then the error appears.

**Comment by ZelphirKaltstahl** [comment]
@krono Yes! That solved it! Thanks for your help! I totally would not have known where to look for the mistake and only when you mentioned write permissions, I remembered once running Squeak as super user for some permission error (which I fixed in another way described on some help page).

After changing the owner and group of the whole Squeak directory to my own account recursively, everything went smoothly.

Now I only need to figure out how I "install something using Metacello" : )

**Comment by krono** [comment]
@ZelphirKaltstahl Thanks for letting us know, I surely must fix this to raise an appropriate error.

Regarding "install something using Metacello": look at <http://squeak.org/projects/> and all the “[Quick Install]” links. All those are Metacello recipes.

(closing here)

**Comment by ZelphirKaltstahl** [comment]
@krono Ah OK thanks! Already did some Koans today and everything is working fine.
