### ISSUE TITLE
The description of the project has a dead link

### ISSUE THREAD

**Issue by jecisc** [dalehenrich/metacello-work#435]
The link in the description of Metacello point to a 404 page.

**Comment by dalehenrich** [comment]
@jecisc could you provide a bit more detail? I'm not sure where the dead link is ...

**Comment by jecisc** [comment]
https://puu.sh/wcQvV/be309872d9.png

**Comment by dalehenrich** [comment]
Hmmm, I don't get a 404 when I click on that link ... but along the way I _am_ redirected to this link: https://code.google.com/archive/p/metacello/ (note the `https`) ... does that link work for you?

**Comment by jecisc** [comment]
This links works for me. Maybe the other does not redirect me because I have some plugins increasing the security of my browsing.

**Comment by dalehenrich** [comment]
I'll plug in the https link ... I wasn't sure whether or not I was seeing the page because I am an owner of that project or not :)
