### ISSUE TITLE
UndeclaredVariableWarning's defaultAction when Metacello loads a project should have option to fail

### ISSUE THREAD

**Issue by macta** [dalehenrich/metacello-work#443]
I submitted a request to SmalltalkCI to fail a build when you get an UndeclaredVariableWarning's 
e.g "
Fetched -> Lambda-cypress.1 --- filetree:///home/travis/build/macta/PharoLambda [:] --- filetree:///home/travis/build/macta/PharoLambda
Lambda class>>processJSON: (NeoJSONReader is Undeclared)

Loaded -> Lambda-cypress.1 --- filetree:///home/travis/build/macta/PharoLambda [:] --- cache
...finished baseline"

I would like my build to fail for missing prequisites (for many this is controversial  - hence it should be an option).

I was told that Metacello generates the above error msg and doesn't fail the load. Is there any way to make an option to fail, such that SmalltalkCI could then leverage this?

**Comment by dalehenrich** [comment]
@macta ... I am under the impression that this was [handled by SmalltalkCI a while ago](https://github.com/hpi-swa/smalltalkCI/issues/64) with [this code](https://github.com/hpi-swa/smalltalkCI/blob/e109441b1871c4cef7842cebfbef083344325619/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class/instance/basicLoadProjectOn..st#L13-L22) ... and [@fniephaus seems to agree](https://github.com/hpi-swa/smalltalkCI/issues/298#issuecomment-313905921) ...
